apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_HOST
        - name: POSTGRES_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_USERNAME            
        - name: POSTGRES_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_PASSWORD            
        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_NAME            
        - name: POSTGRES_DB_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_PORT
        - name: POSTGRES_DB_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_URL
        - name: POSTGRES_USR_TBL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USR_TBL
        ports:
        - containerPort: 5432

        