apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: abhiemin-dev
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: postgresql
  template:
    metadata:
      labels:
        deployment: postgresql
    spec:
      containers:
        - name: postgresql
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/postgresql@sha256:aaf4d9767040dfd9586c48930c1e5b164f0e611361f951933f99149a8d9b3fe0'
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600